FROM python:3.11-slim

WORKDIR /app

# cache dependencies
COPY ../backend/app/requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

# Copy application code
COPY ../backend/app /app

# Create .env file if it doesn't exist
RUN touch /app/.env

# Optionally copy .env if it exists in the build context
# This will not fail if .env doesn't exist
COPY ../backend/app/.env /app/.env 

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]