FROM python:3.11-slim

WORKDIR /app

# cache dependencies
COPY ../backend/app/requirements.txt /app

RUN pip install -r requirements.txt

COPY ../backend/app /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]