name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "v1" ]  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4 # Check out the repositor

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/app
          dockerfile: Dockerfile.backend
          push: true
          tags: akshay0409/prompt-to-course:${{ github.sha }}
